GENERAL:
  manual_seed: 123
  model_dir: model/pointgroup/pointgroup.py
  dataset_dir: data/scannetv2_inst.py

DATA:
  data_root: /home/ubuntu/Code/Manipulation/Bin_Picking/data
  dataset: Sileance_Dataset
  obj_name: gear

  classes: 2
  ignore_label: -100

  input_channel: 3
  scale: 500   # voxel_size = 1 / scale, scale 500(2mm)
  batch_size: 36
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4 # 4=mean

STRUCTURE:
  model_name: pointgroup
  m: 16 # 16 or 32
  block_residual: True
  block_reps: 2

  use_coords: False

TRAIN:
  epochs: 100
  n_workers: 16 # data loader workers
  optim: Adam # Adam or SGD
  lr: 0.001
  lr_milestones: [50]
  multiplier: 0.5
  momentum: 0.9
  weight_decay: 0.0000001
  save_freq: 10  # also eval_freq
  loss_weight: [0., 1.0, 1.0, 1.0] # semantic_loss, offset_norm_loss, offset_dir_loss, score_loss

  fg_thresh: 0.75
  bg_thresh: 0.25

  score_scale: 50 # the minimal voxel size is 2cm
  score_fullscale: 14
  score_mode: 4 # mean

  pretrain_path:
  pretrain_module: []
  fix_module: []

GROUP:
  ### point grouping
  cluster_radius: 0.03
  cluster_meanActive: 50
  cluster_shift_meanActive: 300
  cluster_npoint_thre: 50

  prepare_epochs: 999

TEST:
  ds_size: 0.005
  bandwidth: 0.02
  save_semantic: True
  save_instance: True

